version: '3'


services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "Pavon$31$32"
      POSTGRES_DB: "chipsy-backend"
    container_name: contname
    volumes:
      - ./postgres:/var/lib/postgresql/data